# Generated by Django 5.2.4 on 2025-07-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('student_code', models.CharField(max_length=100, verbose_name='Student Code')),
                ('course', models.CharField(max_length=100, verbose_name='Chosen Course')),
                ('course_code', models.CharField(max_length=100, verbose_name='Course Code')),
                ('major_subject', models.CharField(max_length=100, verbose_name='Major Subject')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
    ]
